# -*- coding: utf-8 -*-
{
    'name' : 'Latihan Addon Academic Odoo',
    'description':'***New Addons Manajemn Software***',
    'version': '1.0',
    'sequence':-100,
    'description': """New AddonsManajemen SOftware""",
    'summary': 'Addons Manajmen Konsol',
    'website':'https://newodoo.com',
    'locense' :'LGPL-3',
    'category': 'Education',
    'depends': [],
    'data': ["menu.xml",
             "course.xml",
             "security/ir.model.access.csv",
             "session.xml"],
    'qweb':[],
    'installable': True,
    'application': True,
    'auto_install': False,
}
